[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/assets/models/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/assets/audio/*.mp3"
  [headers.values]
    Content-Type = "audio/mpeg"
